// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using asdasdasdasd;
//
//    var collectionSkins = CollectionSkins.FromJson(jsonString);

namespace SteamApiJuttu.Models.TradeUpSpy
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CollectionSkins
    {
        [JsonProperty("createTime")]
        public string CreateTime { get; set; }

        [JsonProperty("hasGloves")]
        public bool HasGloves { get; set; }

        [JsonProperty("hasKnives")]
        public bool HasKnives { get; set; }

        [JsonProperty("hasStatTrak")]
        public bool HasStatTrak { get; set; }

        [JsonProperty("iconURL")]
        public Uri IconUrl { get; set; }

        [JsonProperty("idc")]
        public long Idc { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }


        [JsonProperty("skinList")]
        public List<SkinListSkin> SkinList { get; set; }

        [JsonProperty("totalClassified")]
        public long TotalClassified { get; set; }

        [JsonProperty("totalConsumer")]
        public long TotalConsumer { get; set; }

        [JsonProperty("totalCovert")]
        public long TotalCovert { get; set; }

        [JsonProperty("totalIndustrial")]
        public long TotalIndustrial { get; set; }

        [JsonProperty("totalMilSpec")]
        public long TotalMilSpec { get; set; }

        [JsonProperty("totalRestricted")]
        public long TotalRestricted { get; set; }

        [JsonProperty("totalSpecial")]
        public long TotalSpecial { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }






    public partial class SkinListSkin
    {
        [JsonProperty("highestPriceNST")]
        public double HighestPriceNst { get; set; }

        [JsonProperty("ids")]
        public long Ids { get; set; }

        [JsonProperty("inspectURL")]
        public string InspectUrl { get; set; }

        [JsonProperty("lowestPriceNST")]
        public double LowestPriceNst { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("rarity")]
        public string Rarity { get; set; }

        [JsonProperty("skinSnipeId")]
        public long SkinSnipeId { get; set; }

        [JsonProperty("urlImageSteam")]
        public Uri UrlImageSteam { get; set; }

        [JsonProperty("vId")]
        public long VId { get; set; }
    }

    public partial class CollectionSkins
    {
        public static CollectionSkins FromJson(string json) => JsonConvert.DeserializeObject<CollectionSkins>(json, TradeUpSpy.Converter.Settings);
    }

}
